#!/usr/bin/env python3
"""Run a difftest benchmark under gem5 SE mode and emit normalized stats.

This script is the gem5 counterpart of run-cae.py. Flow:

  1. Load + validate the paired YAML via _pairedyaml.
  2. Enforce the gem5 commit pin (tools/cae/check-gem5-version.sh).
  3. Verify the benchmark binary's sha256 against MANIFEST.json; the
     SE-mode variant (<bench>.se.riscv) is what gets handed to gem5.
  4. Launch gem5.opt inside the Docker image that built it. gem5's SE
     workload config is generated by _gem5-se-config.py.
  5. Parse m5out/stats.txt for simInsts / numCycles / simTicks etc.
  6. Emit a JSON report that matches the run-cae.py schema so diff.py
     can consume both without special-casing.

The report is written to --output (default stdout).

Assumptions:
  - The user's Docker daemon has `gem5-build:local` available. The
    image is amd64-native on this host (see the M1 RLCR notes and
    BitLesson BL-20260417-gem5-build-image-arm64-trap for context).
  - `~/gem5` (or $GEM5_ROOT) is the pinned checkout.
  - `build/RISCV/gem5.opt` already exists in the gem5 tree.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _pairedyaml as p  # noqa: E402


REPO_ROOT = p.REPO_ROOT
DEFAULT_DOCKER_IMAGE = "gem5-build:local"
DEFAULT_GEM5_ROOT = Path(os.environ.get("GEM5_ROOT",
                                         str(Path.home() / "gem5")))
SCRIPTS_DIR = REPO_ROOT / "tests" / "cae" / "riscv64" / "difftest" / "scripts"
GEM5_SE_CONFIG = SCRIPTS_DIR / "_gem5-se-config.py"
GEM5_FS_CONFIG = SCRIPTS_DIR / "_gem5-fs-config.py"
CHECK_GEM5_VERSION = REPO_ROOT / "tools" / "cae" / "check-gem5-version.sh"


_STATS_TICK_RE = re.compile(r"^(?P<key>\S+)\s+(?P<val>\S+)")


def _stats_any(stats: dict[str, float], keys: list[str],
               as_float: bool = False):
    """Return the first present key from `keys`, or 0 when none found.

    gem5 stat names vary across CPU types (Atomic / Timing / Minor /
    O3) and protocol families (Classic vs Ruby). Giving a list of
    candidate names lets the CAE side ingest whichever happens to
    land in stats.txt without per-CPU-type special-casing.
    """
    for k in keys:
        if k in stats:
            v = stats[k]
            return float(v) if as_float else int(v)
    return 0.0 if as_float else 0


def _parse_stats(path: Path) -> dict[str, float]:
    if not path.is_file():
        raise FileNotFoundError(f"gem5 stats file missing: {path}")
    out: dict[str, float] = {}
    for line in path.read_text().splitlines():
        line = line.rstrip()
        if not line or line.startswith("-----"):
            continue
        m = _STATS_TICK_RE.match(line)
        if not m:
            continue
        key = m.group("key")
        val = m.group("val")
        try:
            out[key] = float(val)
        except ValueError:
            continue
    return out


def _gem5_mode(cfg: p.PairedConfig) -> str:
    return cfg.gem5_only.get("runtime", {}).get("mode", "se")


def _resolve_elf(cfg: p.PairedConfig) -> Path:
    mode = _gem5_mode(cfg)
    variant = "qemu" if mode == "fs" else "se"
    return p.verify_benchmark(cfg, variant=variant)


def _require_gem5_pin(gem5_root: Path) -> None:
    if not CHECK_GEM5_VERSION.is_file():
        raise FileNotFoundError(f"missing {CHECK_GEM5_VERSION}")
    result = subprocess.run(
        [str(CHECK_GEM5_VERSION), str(gem5_root)],
        cwd=str(REPO_ROOT),
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"gem5 pin check failed (exit {result.returncode})"
        )


def _ensure_gem5_binary(gem5_root: Path) -> None:
    gem5_opt = gem5_root / "build" / "RISCV" / "gem5.opt"
    if not gem5_opt.is_file():
        raise FileNotFoundError(
            f"{gem5_opt} not found; build it with:\n"
            f"  docker run --rm -v {gem5_root}:/gem5 -w /gem5 "
            f"{DEFAULT_DOCKER_IMAGE} bash -c "
            f"'scons build/RISCV/gem5.opt -j$(nproc) --linker=gold'"
        )


def run(cfg: p.PairedConfig, gem5_root: Path, docker_image: str,
        output: Path | None) -> dict[str, object]:
    _require_gem5_pin(gem5_root)
    _ensure_gem5_binary(gem5_root)
    mode = _gem5_mode(cfg)
    elf = _resolve_elf(cfg)
    config_script = GEM5_FS_CONFIG if mode == "fs" else GEM5_SE_CONFIG

    cpu_type = cfg.gem5_cpu_type
    mem_mode = cfg.gem5_mem_mode
    clock = int(cfg.cpu["clock_freq_hz"])
    mem_bytes = int(cfg.memory["dram_size"])
    gem5_mem = cfg.gem5_only.get("memory", {})
    dram_latency_ns = int(gem5_mem.get("dram_latency_ns", 50))
    # SystemXBar latency: default 0 for AtomicCPU (keep numCycles
    # dominated by retirement), honour the YAML knob otherwise.
    default_xbar = 0 if cpu_type == "AtomicCPU" else 1
    xbar_response_ns = int(gem5_mem.get("response_latency_ns",
                                        default_xbar))

    l1i = gem5_mem.get("l1i", {})
    l1d = gem5_mem.get("l1d", {})
    enable_l1 = bool(l1i) or bool(l1d)

    work_dir = Path(tempfile.mkdtemp(
        prefix=f"gem5-{cfg.name}-{cfg.benchmark['name']}-",
        dir=tempfile.gettempdir(),
    ))

    config_inside = (
        f"/cae-qemu/{config_script.relative_to(REPO_ROOT)}"
    )
    elf_inside = (
        f"/cae-qemu/{elf.relative_to(REPO_ROOT)}"
    )

    cmd = [
        "docker", "run", "--rm",
        "-v", f"{gem5_root}:/gem5",
        "-v", f"{REPO_ROOT}:/cae-qemu",
        "-v", f"{work_dir}:/m5out",
        "-w", "/m5out",
        docker_image,
        "/gem5/build/RISCV/gem5.opt",
        "-d", "/m5out",
        config_inside,
        "--binary", elf_inside,
        "--cpu-type", cpu_type,
        "--clock-hz", str(clock),
        "--mem-bytes", str(mem_bytes),
        "--mem-mode", mem_mode,
        "--dram-latency-ns", str(dram_latency_ns),
        "--xbar-response-ns", str(xbar_response_ns),
    ]
    if enable_l1:
        cmd.extend([
            "--enable-l1", "true",
            "--l1i-size", str(l1i.get("size", "32kB")),
            "--l1i-assoc", str(l1i.get("assoc", 2)),
            "--l1i-hit-cycles", str(l1i.get("latency_hit_cycles", 1)),
            "--l1i-miss-cycles", str(l1i.get("latency_miss_cycles", 10)),
            "--l1d-size", str(l1d.get("size", "32kB")),
            "--l1d-assoc", str(l1d.get("assoc", 2)),
            "--l1d-hit-cycles", str(l1d.get("latency_hit_cycles", 1)),
            "--l1d-miss-cycles", str(l1d.get("latency_miss_cycles", 10)),
        ])

    if mode == "fs":
        bench_name = cfg.benchmark["name"]
        manifest = p.load_manifest()
        entry = manifest["benchmarks"].get(bench_name, {})
        approx = int(entry.get("expected_insns_approx", 0))
        if approx > 0:
            ticks_per_cycle = 1000
            max_ticks = int(approx * 3 * ticks_per_cycle)
            cmd.extend(["--max-ticks", str(max_ticks)])

    t0 = time.monotonic()
    result = subprocess.run(cmd, capture_output=True, text=True)
    wallclock = time.monotonic() - t0
    if result.returncode != 0:
        raise RuntimeError(
            f"gem5 invocation failed (exit {result.returncode}):\n"
            f"  stdout: {result.stdout[-500:]}\n"
            f"  stderr: {result.stderr[-500:]}"
        )

    stats_path = work_dir / "stats.txt"
    stats = _parse_stats(stats_path)

    total_insns = int(stats.get("simInsts", 0))
    num_cycles = int(stats.get("system.cpu.numCycles", 0))

    # Secondary metrics — sourced from gem5 stats.txt. Field names
    # differ across CPU types, so probe multiple candidates and fall
    # back to 0 when a stat is not present. Aggregation matches the
    # CAE side so diff.py compares the same units.
    bp_pred = _stats_any(stats, [
        "system.cpu.branchPred.condPredicted",
        "system.cpu.branchPred.lookups::total",
        "system.cpu.branchPred.lookups",
    ])
    bp_incorrect = _stats_any(stats, [
        "system.cpu.branchPred.condIncorrect",
        "system.cpu.branchPred.mispredicted::total",
        "system.cpu.branchPred.mispredicted",
    ])
    mispredict_rate = (float(bp_incorrect) / bp_pred) if bp_pred else 0.0

    dc_hits = _stats_any(stats, [
        "system.cpu.dcache.demandHits::total",
        "system.cpu.dcache.ReadReq.hits::total",
        "system.cpu.dcache.overallHits::total",
    ])
    dc_misses = _stats_any(stats, [
        "system.cpu.dcache.demandMisses::total",
        "system.cpu.dcache.ReadReq.misses::total",
        "system.cpu.dcache.overallMisses::total",
    ])
    l1d_mpki = (1000.0 * dc_misses / total_insns) if total_insns else 0.0

    # avg_load_latency contract: average latency per LOAD access, in
    # CPU cycles, measured on both backends identically.
    #
    # Round-4 narrows the metric from "per-demand-access" (load + store
    # + AMO) to "per-load" because the plan's AC-4 metric is explicitly
    # "average load latency" — stores should not inflate it. On gem5,
    # use `ReadReq.*` stat variants which filter to loads only.  CAE's
    # run-cae.py side mirrors this via load_hits / load_misses /
    # load_stall_cycles split out from the aggregate L1D counters.
    sim_freq = int(stats.get("simFreq", 1_000_000_000_000))
    ticks_per_cycle = (sim_freq / clock) if clock else 0.0

    load_hits = _stats_any(stats, [
        "system.cpu.dcache.ReadReq.hits::total",
        "system.cpu.dcache.ReadReq.hits::cpu.data",
    ])
    load_misses = _stats_any(stats, [
        "system.cpu.dcache.ReadReq.misses::total",
        "system.cpu.dcache.ReadReq.misses::cpu.data",
    ])
    total_load_miss_ticks = _stats_any(stats, [
        "system.cpu.dcache.ReadReq.missLatency::total",
        "system.cpu.dcache.ReadReq.missLatency::cpu.data",
    ], as_float=True)
    total_load_hit_ticks = _stats_any(stats, [
        "system.cpu.dcache.ReadReq.hitLatency::total",
        "system.cpu.dcache.ReadReq.hitLatency::cpu.data",
    ], as_float=True)
    total_load_accesses = load_hits + load_misses
    total_load_latency_ticks = total_load_miss_ticks + total_load_hit_ticks
    if total_load_accesses > 0 and ticks_per_cycle > 0:
        avg_load_latency = (total_load_latency_ticks / total_load_accesses
                            / ticks_per_cycle)
    else:
        avg_load_latency = 0.0

    per_cpu = {
        "cpu_index": 0,
        "cycles": num_cycles,
        "insns": total_insns,
        "stall_cycles": 0,
        "ipc": (total_insns / num_cycles) if num_cycles else 0.0,
        "bpred_predictions": bp_pred,
        "bpred_mispredictions": bp_incorrect,
        "mispredict_rate": mispredict_rate,
        "l1d_hits": dc_hits,
        "l1d_misses": dc_misses,
        "l1d_mpki": l1d_mpki,
        "load_hits": load_hits,
        "load_misses": load_misses,
        "avg_load_latency": avg_load_latency,
    }
    cpus = [per_cpu]
    aggregate = {
        "total_cycles": num_cycles,
        "total_insns": total_insns,
        "ipc": (total_insns / num_cycles) if num_cycles else 0.0,
        "mispredict_rate": mispredict_rate,
        "l1d_mpki": l1d_mpki,
        "avg_load_latency": avg_load_latency,
    }

    report: dict[str, object] = {
        "schema_version": 1,
        "config_name": cfg.common["contract"]["config_name"],
        "benchmark": cfg.benchmark["name"],
        "backend": "gem5",
        "backend_variant": cpu_type,
        "num_cpus": 1,
        "clock_freq_hz": clock,
        "sample_stats_at": cfg.measurement.get("sample_stats_at", "ebreak"),
        "cpus": cpus,
        "aggregate": aggregate,
        "wallclock_seconds": wallclock,
        "gem5": {
            "simInsts": total_insns,
            "simTicks": int(stats.get("simTicks", 0)),
            "simFreq": int(stats.get("simFreq", 0)),
            "hostSeconds": float(stats.get("hostSeconds", 0.0)),
        },
    }

    if output is not None:
        output.parent.mkdir(parents=True, exist_ok=True)
        with output.open("w") as f:
            json.dump(report, f, indent=2, sort_keys=False)
            f.write("\n")

    # Clean up temp m5out unless caller requested --keep-workdir.
    # We keep stats.txt under reports/ if --output was given so users can
    # still debug — leave removal to the driver shell script.
    shutil.rmtree(work_dir, ignore_errors=True)
    return report


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("config")
    ap.add_argument("--benchmark")
    ap.add_argument("--output", type=Path)
    ap.add_argument("--gem5-root", type=Path, default=DEFAULT_GEM5_ROOT)
    ap.add_argument("--docker-image", default=DEFAULT_DOCKER_IMAGE)
    args = ap.parse_args()

    cfg = p.load_config(args.config)
    if args.benchmark:
        cfg.benchmark.setdefault("_original_name", cfg.benchmark["name"])
        cfg.benchmark["name"] = args.benchmark
    report = run(cfg, args.gem5_root, args.docker_image, args.output)
    if args.output is None:
        json.dump(report, sys.stdout, indent=2, sort_keys=False)
        sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
